Sqlite3 v5
mtxr/vscode-sqltools pull request #953
Opened 2022-09-05 11:47 UTC by gjsjohnmurray

Use sqlite@5.0.10 instead of @4.2.0

2022-09-05 11:54 UTC, gjsjohnmurray commented
@mtxr the aim of this PR is to resolve #858 and maybe #921.

I had also hoped to remove the need for install-time dependency resolution and building (see commit history of the PR), but failed at this so reverted that experiment's three commits.

The branch passed basic testing I performed using the /test/project.code-workspace

2022-09-05 15:00 UTC, gjsjohnmurray commented
Zip of a manual build of the driver VSIX from this PR.

[sqltools-driver-sqlite-0.3.1-dev.953.zip](https://github.com/mtxr/vscode-sqltools/files/9490794/sqltools-driver-sqlite-0.3.1-dev.953.zip)

2022-09-07 13:30 UTC, mtxr requested changes

2022-09-07 13:30 UTC, mtxr commented on packages/driver.sqlite/package.json
> +  },
```suggestion
```

This is not necessary since the extension install it in run time

2022-09-07 13:30 UTC, mtxr commented on packages/driver.sqlite/src/ls/driver.ts
> +const SQLite3Version = '5.0.10';
```suggestion
const SQLite3Version = '5.0.11';
```

2022-09-07 13:54 UTC, mtxr approved these changes

2022-09-07 14:06 UTC, merged